cash_in:
  legal:
    fee_percentage: 0.0003
    fee_maximum_amount: 5
  natural:
    fee_percentage: 0.0003
    fee_maximum_amount: 5
cash_out:
  legal:
    fee_percentage: 0.003
    fee_minimum_amount: 0.5
  natural:
    fee_percentage: 0.003
    free_of_charge_amount: 1000
    free_of_charge_number_of_operations: 3